### ISSUE TITLE
js에 나는 빨간줄 에러는 버전 문제  그냥 작동에 영향 없음.

### ISSUE THREAD

**Issue by seong9566** [seong9566/miniproject#55]
이 문제는 버전 문제로 추후 VS코드 작업 할 것이기 때문에 무시해도 됨.

**Comment by BeomyoonHeo** [comment]
js 옵셔널체이닝 사용시 해당 문제 발생하는 것으로 확인됩니다. 아마 sts 스크립트 읽는 툴이 버전이 낮아서 그런거 같아요
